name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: djibril-marega
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/djibril-marega/portfolio:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform -chdir=terraform init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Plan
        run: terraform -chdir=terraform plan
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

      - name: Get Terraform output
        id: tf_output
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: |
          HOSTNAME=$(terraform -chdir=terraform output -raw instance_app_hostname)
          if [ -z "$HOSTNAME" ]; then
            echo "Terraform output is empty or failed"
            exit 1
          fi
          # Ajouter dans le job env pour les steps suivants
          echo "EC2_HOSTNAME=$HOSTNAME" >> $GITHUB_ENV
          # DÃ©finir comme output du step
          echo "EC2_HOSTNAME=$HOSTNAME" >> $GITHUB_OUTPUT


      - name: Create/update repo secret
        env:
          GH_TOKEN: ${{ secrets.GHCR_PAT }}
          EC2_HOSTNAME: ${{ steps.tf_output.outputs.EC2_HOSTNAME }}
        run: |
          gh secret set EC2_HOSTNAME --body "$EC2_HOSTNAME" --repo $GITHUB_REPOSITORY

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible & dependencies
        run: |
          pip install ansible boto3 botocore
          ansible-galaxy collection install community.general

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yaml -i "${EC2_HOSTNAME}," --user ubuntu --private-key ec2_key.pem
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
          EC2_HOSTNAME: ${{ env.EC2_HOSTNAME }}

      - name: Show EC2 Hostname
        run: echo "EC2 instance hostname $EC2_HOSTNAME"
